### PR TITLE
[Bug] Fix in app browser security issue

### PR DESCRIPTION
**Pull request by jeden**
https://github.com/Outblock/FRW-iOS/issues/485

image
image

### CODE REVIEW

**Comment by lmcmz** [comment]
Nice work, we do have some other place also use the url. 
Probably, we could change them all together. if it's possible.
https://github.com/search?q=repo%3AOutblock%2FFRW-iOS%20webVC%3F.webView.url&type=code

**Review by lmcmz — CHANGES_REQUESTED** [review]
For other scenario, we don't have the example url yet. 
Currently, this one is only for EVM authn

**Comment by jeden** [comment]
> Nice work, we do have some other place also use the url. Probably, we could change them all together. if it's possible. https://github.com/search?q=repo%3AOutblock%2FFRW-iOS%20webVC%3F.webView.url&type=code

I think I covered all cases — however I couldn't test all of them as not sure how to trigger each individual case. Any suggestion, if you think it's needed?

**Comment by lmcmz** [comment]
I think it should be fine, it's a bit hard to simulate the snoof in all cause. 
We just make sure if the normal flow is working, then it should be fine.

**Review by lmcmz — APPROVED** [review]

**Pull request merged**
